### ISSUE TITLE
create a release 

### ISSUE THREAD

**Issue by glipka** [ryanhefner/Array.prototype.findIndex#1]
Hi 
I try to to create a webjar from  Array.prototype.findIndex  (www.webjars.org/npm) but a release is necessary
Is it possible to create a release (0.1.0) 
Thanks for your help

**Comment by ryanhefner** [comment]
@glipka I think that was a Github issue. A release was made back in May, but for some reason wasn't showing up. Looks like it's there now. Sorry to the belated response.
